export { run, type RunOptions, type RunResult } from './launcher';
export { readTrace, writeTrace, UserError } from './core/io';
export { TraceSchema, EventSchema, ValueSchema, SCHEMA_VERSION, TOOL_VERSION } from './core/schema';
export type { Trace, Observation, SafeValue, Origin, Coverage, ProcessInfo, ComparisonKey } from './core/schema';
export { createComparisonKey, writeComparisonKey, readComparisonKey } from './core/privacy';
export { evidenceFor, explainText, diffTraces, diffText, compareValue } from './core/analyze';
export type { TraceDiff, KeyEvidence, Equality, DiffRow } from './core/analyze';
export { renderTraceHtml, renderDiffHtml } from './report/html';
export { readExportPolicy, sanitizeTraces, exportArtifacts, ExportPolicySchema, type ExportPolicy } from './core/export';
export { getActiveRecorder, type ConfigTraceAdapter, type AdapterContext } from './runtime/api';
export { buildProvenance } from './analysis/provenance';
export type { ProvenanceGraph, ProvenanceNode, ProvenanceEdge, ProvenanceOptions, EvidenceConfidence } from './analysis/provenance';
export { diagnoseTraces, diagnosisText } from './analysis/diagnose';
export type { Diagnosis, DiagnosisFinding, DiagnosisOptions } from './analysis/diagnose';
export { verifyTrace, verificationText, readVerificationPolicy, VerificationPolicySchema } from './analysis/policy';
export type { VerificationPolicy, VerificationResult, VerificationCheck } from './analysis/policy';
export { analyzeHistory, readHistory, addHistory, historyText } from './analysis/history';
export type { HistoryAnalysis, HistoryEntry, DriftChange } from './analysis/history';
export { adapterCatalog, DOTENV_MANIFEST, NATIVE_ENV_MANIFEST } from './adapters/registry';
export { AdapterManifestSchema } from './core/schema';
export type { AdapterManifest, AdapterDeclaration } from './core/schema';
export { markFailureBoundary } from './runtime/api';
export { EvidenceMcpServer, loadAuthorizedTraces, serveMcp } from './agent/server';

export { TraceIndex, buildTraceIndex } from './core/event-index';
export type { ComparisonIndexes } from './core/event-index';
